// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA409A8pPOxFflKQvqqgI_mMYPb1AdS-bA',
    appId: '1:204612081594:web:5b7da13e091c68c961af83',
    messagingSenderId: '204612081594',
    projectId: 'harrypotter-memorymaster',
    authDomain: 'harrypotter-memorymaster.firebaseapp.com',
    storageBucket: 'harrypotter-memorymaster.appspot.com',
    measurementId: 'G-HYMLZGV90H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDPRzZnycTbnA1Mr3v4xA7l94-Rs6OjaU',
    appId: '1:204612081594:android:bf5023a4ceea05f561af83',
    messagingSenderId: '204612081594',
    projectId: 'harrypotter-memorymaster',
    storageBucket: 'harrypotter-memorymaster.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClE_aifDG0B2LHY0yeuNyjSK-eDyRyMN8',
    appId: '1:204612081594:ios:2c08c499033547de61af83',
    messagingSenderId: '204612081594',
    projectId: 'harrypotter-memorymaster',
    storageBucket: 'harrypotter-memorymaster.appspot.com',
    iosClientId: '204612081594-g8mfo7g41670l78pijn4sfi3mp85u3q2.apps.googleusercontent.com',
    iosBundleId: 'com.example.yazlabb13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClE_aifDG0B2LHY0yeuNyjSK-eDyRyMN8',
    appId: '1:204612081594:ios:2c08c499033547de61af83',
    messagingSenderId: '204612081594',
    projectId: 'harrypotter-memorymaster',
    storageBucket: 'harrypotter-memorymaster.appspot.com',
    iosClientId: '204612081594-g8mfo7g41670l78pijn4sfi3mp85u3q2.apps.googleusercontent.com',
    iosBundleId: 'com.example.yazlabb13',
  );
}
